---
- name: Add composer repository
  apt_repository:
    repo: ppa:jbboehr/composer

- name: Install required packages
  apt:
    name: "{{ item }}"
  with_items:
    - composer

- name: Create install folder
  file:
    path: "{{ engelsystem_install_path }}"
    state: directory
    owner: "{{ engelsystem_user }}"
    group: "{{ engelsystem_group }}"
    mode: 0755

- name: Clone repository
  git:
    repo: 'https://github.com/engelsystem/engelsystem.git'
    dest: "{{ engelsystem_install_path }}"
    depth: 1
    update: true
    version: "{{ engelsystem_version }}"
  become: yes
  become_user: "{{ engelsystem_user }}"

- name: Run composer install
  composer:
    command: install
    working_dir: "{{ engelsystem_install_path }}"
    no_dev: true

- name: Run composer dump-autoload
  composer:
    command: dump-autoload
    working_dir: "{{ engelsystem_install_path }}"

- name: Create a new database with name '{{ engelsystem_mysql_database }}'
  mysql_db:
    name: "{{ engelsystem_mysql_database }}"
    state: present
  register: database_created

- name: Create mariadb user
  mysql_user:
    name: "{{ engelsystem_mysql_user }}"
    password: "{{ engelsystem_mysql_password }}"
    priv: '{{ engelsystem_mysql_database }}.*:ALL,GRANT'
    state: present

- name: Import sql files
  mysql_db:
    state: import
    name: "{{ engelsystem_mysql_database }}"
    target: "{{ engelsystem_install_path }}/db/install.sql"
  when: database_created.changed

- name: Import sql files
  mysql_db:
    state: import
    name: "{{ engelsystem_mysql_database }}"
    target: "{{ engelsystem_install_path }}/db/update.sql"
  when: database_created.changed

- name: Copy configuration file
  template:
    src: config.php.j2
    dest: "{{ engelsystem_install_path }}/config/config.php"
    owner: "{{ engelsystem_user }}"
    group: "{{ engelsystem_group }}"
    mode: 0660

