---
- name: Install nginx and PHP
  apt:
    name: "{{ item }}"
  with_items:
    - nginx-full
    - php7.0-fpm
  when: ansible_pkg_mgr == "apt"

- name: Copy nginx configuration file
  template:
    backup: yes
    dest: /etc/nginx/nginx.conf
    src: nginx.conf.j2
  notify: Reload nginx

- name: Start and enable nginx
  systemd:
    name: nginx.service
    enabled: yes
    state: running
