---
- name: Reload nginx
  systemd:
    daemon_reload: yes
    name: nginx.service
    state: reloaded
  listen: reload nginx
- name: grant nginx read access
  file:
    path: /opt/engelsystem
    mode: u=rwX,g=rwX,o=rX
    owner: root
    group: root
    recurse: yes
  listen: engelsystem updated
- name: grant nginx write access to '/import'
  file:
    path: /opt/engelsystem/import
    mode: u=rwX,g=rwX,o=rX
    owner: root
    group: www-data
    recurse: yes
  listen: engelsystem updated
- name: create engelsystem database
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: engelsystem
    state: present
  listen: engelsystem updated
- name: install database
  shell: cat /opt/engelsystem/db/install.sql /opt/engelsystem/db/update.sql | mysql -B engelsystem
  listen: engelsystem updated
- name: create engelsystem user
  mysql_user:
    name: engelsystem
    password: engelsystem
    priv: engelsystem.*:ALL,GRANT
    login_unix_socket: /var/run/mysqld/mysqld.sock
  listen: engelsystem updated
